name: Context Explorer
on: [push, pull_request]

jobs:
  explore-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      
      - name: Conditional execution
        if: github.event_name == 'push'
        run: echo "This runs only on push events"
        
